// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQlSU-8UjB4acyjWQOC9lDzXOllyZeVY0',
    appId: '1:311250277102:web:d2ce6e949c3bbafcbf59ff',
    messagingSenderId: '311250277102',
    projectId: 'criadourobozzi',
    authDomain: 'criadourobozzi.firebaseapp.com',
    storageBucket: 'criadourobozzi.appspot.com',
    measurementId: 'G-VVS9P0S9KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKFJZXuBI2p-m1ggqHzmDyRiI6BgrA5d4',
    appId: '1:311250277102:android:137a1da11215461bbf59ff',
    messagingSenderId: '311250277102',
    projectId: 'criadourobozzi',
    storageBucket: 'criadourobozzi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_iGoUYJD1uOScqhl4geyDFG-mSZ3UMRE',
    appId: '1:311250277102:ios:0d7268b4620d782dbf59ff',
    messagingSenderId: '311250277102',
    projectId: 'criadourobozzi',
    storageBucket: 'criadourobozzi.appspot.com',
    iosClientId: '311250277102-bj03p9a53gbl34p9bqn2b53vq7euq52s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_iGoUYJD1uOScqhl4geyDFG-mSZ3UMRE',
    appId: '1:311250277102:ios:eed60b9c3bf71526bf59ff',
    messagingSenderId: '311250277102',
    projectId: 'criadourobozzi',
    storageBucket: 'criadourobozzi.appspot.com',
    iosClientId: '311250277102-t7ae1m8g5j5hqt0o5kncs4o80d36mc7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.ris.RunnerTests',
  );
}
